version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:8.0
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Run unit tests and generate coverage report
          command: mvn test jacoco:report
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  deploy-docs:
    executor: maven-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:EUtKI4mcV9G21S5yNlEVHL/8bA58a+Rir9gLuBgO17c"
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            # Configurer les informations utilisateur Git
            git config --global user.email "ybodount84@gmail.com"
            git config --global user.name "YoussefBOUDOUNTCeri"
            # Cloner la branche gh-pages en utilisant l'URL SSH
            git clone --branch gh-pages git@github.com:YoussefBOUDOUNTCeri/ceri-m1-techniques-de-test.git gh-pages
            # Copier les fichiers Javadoc générés dans le dépôt cloné
            cp -R target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Auto-update Javadoc"
            # Pousser les changements vers gh-pages
            git push origin gh-pages

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy-docs:
          requires:
            - build
          filters:
            branches:
              only:
                - master
