version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Run unit tests and generate coverage report
          command: mvn test jacoco:report
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  deploy-docs:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.email "ybodount84@gmail.com"
            git config --global user.name "YoussefBOUDOUNTCeri"
            git clone --branch gh-pages https://$GITHUB_TOKEN@github.com/YoussefBOUDOUNTCeri/ceri-m1-techniques-de-test.git gh-pages
            cp -R target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Auto-update Javadoc"
            git push origin gh-pages

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy-docs:
          filters:
            branches:
              only:
                - master