# version: 2.1

# executors:
#   maven-executor:
#     docker:
#       - image: circleci/openjdk:8-jdk
#     working_directory: ~/repo

# jobs:
#   build:
#     executor: maven-executor
#     steps:
#       - checkout
#       - run:
#           name: Install dependencies
#           command: mvn install -DskipTests
#       - run:
#           name: Run unit tests
#           command: mvn test

# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - build:
#         filters:
#           branches:
#             only:
#               - master

version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests
      - run:
          name: Run unit tests and generate coverage report
          command: mvn test jacoco:report
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
