version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests
      - run:
          name: Run unit tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only: master